services:
  - type: static
    name: artefactos-del-ayer
    env: node
    buildCommand: |
      cd frontend
      npm install -g @angular/cli
      npm install
      ng build --configuration production
    staticPublishPath: frontend/dist/artefactos-del-ayer
